### ISSUE TITLE
Support Google Gemini API as a Provider

### ISSUE THREAD

**Issue by adhintz** [block-open-source/goose#129]
Copying from @shanehuntley's original issue in the previous repo:
> Support Google Gemini as a provider via Gemini API
https://ai.google.dev/gemini-api

Remaining tasks from the PR review:

- [x] change to vcr tests. @codefromthecrypt has done this in #118 
- [x] try vision model. Requires the images to be encoded.
- [x] add to pyproject.toml
- [ ] add vcr tests for vision. @codefromthecrypt has done this in https://github.com/adhintz/goose/pull/1

**Comment by lilydelalande** [comment]
Looks like this can be closed? Latest merged PR seems to the the VCR tests for vision

**Comment by codefromthecrypt** [comment]
has integration tests, but not the vcr ones. they'll be in soon
